{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vm-inventory.fullname" . }}-postgres
spec:
  serviceName: {{ include "vm-inventory.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.postgresql.database }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgresql.username }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgresql.password }}"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.postgresql.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vm-inventory.fullname" . }}-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
{{- end }}
