apiVersion: v1
kind: ConfigMap
metadata:
  name: vm-inventory-config
  labels:
    app.kubernetes.io/name: vm-inventory
data:
  GCP_CLIENT_MODE: "mock"
  GCP_SYNC_INTERVAL: "300000"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    app.kubernetes.io/name: vm-inventory
type: Opaque
stringData:
  username: admin
  password: password
  jwt-secret: vm-artifact-inventory-secret-key-32-chars-long-minimum!
